#!/usr/bin/env python3
"""Validate OTodo's generated source metadata and actual signed bundle graph."""

import argparse
from pathlib import Path
import plistlib
import re
import sys

import yaml

from ci_runtime import CommandError, annotate, run_command

APP_GROUP = "group.plastickarma.otodo"
# target, bundle identifier, embedded path, entitlement source, extension point
COMPONENTS = (
    ("OTodo", "plastickarma.otodo", ".", "OTodoApp/OTodo.entitlements", None),
    ("OTodoWidget", "plastickarma.otodo.widget", "PlugIns/OTodoWidget.appex", "OTodoWidget/OTodoWidget.entitlements", "com.apple.widgetkit-extension"),
    ("OTodoShareExtension", "plastickarma.otodo.share", "PlugIns/OTodoShareExtension.appex", "OTodoShareExtension/OTodoShareExtension.entitlements", "com.apple.share-services"),
    ("OTodoWatch", "plastickarma.otodo.watchkitapp", "Watch/OTodoWatch.app", "OTodoWatch/OTodoWatch.entitlements", None),
    ("OTodoWatchWidget", "plastickarma.otodo.watchkitapp.widget", "Watch/OTodoWatch.app/PlugIns/OTodoWatchWidget.appex", "OTodoWatchWidget/OTodoWatchWidget.entitlements", "com.apple.widgetkit-extension"),
)
ORIENTATIONS = {
    "UIInterfaceOrientationPortrait",
    "UIInterfaceOrientationPortraitUpsideDown",
    "UIInterfaceOrientationLandscapeLeft",
    "UIInterfaceOrientationLandscapeRight",
}
VERSION_PATTERN = r"[0-9]+(?:\.[0-9]+){0,2}"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def load_project(root: Path = Path(".")) -> dict:
    with (root / "project.yml").open(encoding="utf-8") as source:
        project = yaml.safe_load(source)
    require(isinstance(project, dict) and isinstance(project.get("targets"), dict),
            "project.yml must declare the OTodo targets")
    return project


def read_plist(path: Path) -> dict:
    with path.open("rb") as source:
        value = plistlib.load(source)
    require(isinstance(value, dict), f"{path}: expected a plist dictionary")
    return value


def validate_groups(entitlements: dict, label: str) -> None:
    require(isinstance(entitlements, dict) and entitlements.get("com.apple.security.application-groups") == [APP_GROUP],
            f"{label}: effective App Groups must contain only {APP_GROUP}")


def validate_metadata(info: dict, target: str, extension_point: str | None, label: str) -> None:
    require(info.get("CFBundleDisplayName") == "OTodo", f"{label}: CFBundleDisplayName must be OTodo")
    if extension_point:
        extension = info.get("NSExtension")
        require(isinstance(extension, dict) and extension.get("NSExtensionPointIdentifier") == extension_point,
                f"{label}: NSExtensionPointIdentifier must be {extension_point}")
    if target == "OTodo":
        for key in ("UISupportedInterfaceOrientations", "UISupportedInterfaceOrientations~ipad"):
            actual = info.get(key)
            require(isinstance(actual, list) and set(actual) == ORIENTATIONS,
                    f"{label}: {key} must contain all four interface orientations")
        require(isinstance(info.get("UILaunchScreen"), dict), f"{label}: UILaunchScreen must be a dictionary")
    elif target == "OTodoWatch":
        for key, expected in {
            "WKApplication": True,
            "WKCompanionAppBundleIdentifier": "plastickarma.otodo",
            "WKRunsIndependentlyOfCompanionApp": False,
        }.items():
            require(info.get(key) == expected and type(info.get(key)) is type(expected),
                    f"{label}: {key} must be {expected!r}")


def validate_source(root: Path = Path(".")) -> None:
    project = load_project(root)
    default_versions = set()
    default_builds = set()
    for target, identifier, _, entitlement_path, extension_point in COMPONENTS:
        definition = project["targets"].get(target, {})
        settings = definition.get("settings", {}).get("base", {})
        label = f"project.yml target {target}"
        require(settings.get("PRODUCT_BUNDLE_IDENTIFIER") == identifier,
                f"{label}: PRODUCT_BUNDLE_IDENTIFIER must be {identifier}")
        require(settings.get("CODE_SIGN_ENTITLEMENTS") == entitlement_path,
                f"{label}: CODE_SIGN_ENTITLEMENTS must be {entitlement_path}")
        require(definition.get("platform") == ("watchOS" if target.startswith("OTodoWatch") else "iOS"),
                f"{label}: incorrect target platform")
        default_versions.add(str(settings.get("MARKETING_VERSION", "")))
        default_builds.add(str(settings.get("CURRENT_PROJECT_VERSION", "")))
        source_info = definition.get("info", {})
        info = source_info.get("properties", {})
        require(isinstance(info, dict), f"{label}: missing Info.plist properties")
        # Plists are generated by XcodeGen, not committed. Validate their source on
        # Linux, and the generated files as well whenever generation has occurred.
        candidates = [(info, label)]
        info_path = source_info.get("path")
        require(isinstance(info_path, str) and bool(info_path), f"{label}: missing Info.plist path")
        generated = root / info_path
        if generated.exists():
            candidates.append((read_plist(generated), str(generated)))
        for candidate, candidate_label in candidates:
            validate_metadata(candidate, target, extension_point, candidate_label)
            for key, expected in {
                "CFBundleShortVersionString": "$(MARKETING_VERSION)",
                "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
            }.items():
                require(candidate.get(key) == expected, f"{candidate_label}: {key} must use {expected}")
        validate_groups(read_plist(root / entitlement_path), entitlement_path)
        if target == "OTodo":
            # XcodeGen's iOS application default is both iPhone and iPad.
            family = str(settings.get("TARGETED_DEVICE_FAMILY", "1,2")).replace(" ", "")
            require(family == "1,2", f"{label}: must support both iPhone and iPad")
    require(len(default_versions) == 1 and re.fullmatch(VERSION_PATTERN, next(iter(default_versions))) is not None,
            "All five targets must share a valid default MARKETING_VERSION")
    require(len(default_builds) == 1 and re.fullmatch(r"[0-9]+", next(iter(default_builds))) is not None,
            "All five targets must share a numeric CURRENT_PROJECT_VERSION")
    print("Source metadata and App Group declarations validated for all five components.")


def validate_built(app: Path, platform: str = "simulator", expected_version: str | None = None,
                   expected_build: str | None = None) -> None:
    app_info = read_plist(app / "Info.plist")
    version = app_info.get("CFBundleShortVersionString")
    build = app_info.get("CFBundleVersion")
    require(isinstance(version, str) and re.fullmatch(VERSION_PATTERN, version) is not None,
            f"{app}: invalid marketing version {version!r}")
    require(isinstance(build, str) and re.fullmatch(r"[0-9]+", build) is not None,
            f"{app}: invalid build number {build!r}")
    require(expected_version is None or version == expected_version,
            f"{app}: marketing version {version!r} does not match requested {expected_version!r}")
    require(expected_build is None or build == expected_build,
            f"{app}: build {build!r} does not match requested {expected_build!r}")
    require(set(app_info.get("UIDeviceFamily", [])) == {1, 2}, f"{app}: must support both iPhone and iPad")
    for target, identifier, relative_path, _, extension_point in COMPONENTS:
        bundle = app / relative_path
        info = app_info if relative_path == "." else read_plist(bundle / "Info.plist")
        validate_metadata(info, target, extension_point, str(bundle))
        for key, expected in {
            "CFBundleIdentifier": identifier,
            "CFBundleShortVersionString": version,
            "CFBundleVersion": build,
        }.items():
            require(info.get(key) == expected, f"{bundle}: {key} must be {expected!r}, got {info.get(key)!r}")
        watch = target.startswith("OTodoWatch")
        expected_platform = ("watchsimulator" if watch else "iphonesimulator") if platform == "simulator" else ("watchos" if watch else "iphoneos")
        require(info.get("DTPlatformName") == expected_platform,
                f"{bundle}: DTPlatformName must be {expected_platform}, got {info.get('DTPlatformName')!r}")
        executable = info.get("CFBundleExecutable")
        require(isinstance(executable, str) and bool(executable) and Path(executable).name == executable,
                f"{bundle}: missing or invalid CFBundleExecutable")
        binary = bundle / executable
        require(binary.is_file() and binary.stat().st_size > 0 and bool(binary.stat().st_mode & 0o111),
                f"{bundle}: missing, empty, or non-executable binary {executable}")
        run_command(["codesign", "--verify", "--strict", str(bundle)],
                    stage=f"metadata-{target}-signature", timeout=30)
        signed = run_command(["codesign", "--display", "--entitlements", ":-", str(bundle)],
                             stage=f"metadata-{target}-entitlements", timeout=30, capture=True)
        try:
            entitlements = plistlib.loads(signed.encode("utf-8"))
        except (ValueError, plistlib.InvalidFileException) as error:
            raise ValueError(f"{bundle}: codesign did not return effective signed entitlements") from error
        validate_groups(entitlements, str(bundle))
    print(f"Validated all five signed {platform} bundles: {version} ({build}).")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("source")
    built = commands.add_parser("built")
    built.add_argument("--app", required=True, type=Path)
    built.add_argument("--platform", choices=("simulator", "archive"), default="simulator")
    built.add_argument("--expected-version")
    built.add_argument("--expected-build")
    arguments = parser.parse_args()
    if arguments.command == "source":
        validate_source()
    else:
        validate_built(arguments.app, arguments.platform, arguments.expected_version, arguments.expected_build)


if __name__ == "__main__":
    try:
        main()
    except CommandError as error:
        annotate("error", str(error), title="Bundle metadata validation")
        raise SystemExit(error.returncode)
    except (OSError, ValueError, TypeError, yaml.YAMLError) as error:
        annotate("error", str(error), title="Bundle metadata validation")
        raise SystemExit(1)
